### ISSUE TITLE
Commits are not associated properly to GitHub user (email)

### ISSUE THREAD

**Issue by galenandrew** [druc/todo-cli#1]
It appears that you do not have your local git email address added to your GitHub user, which causes your commits to be orphaned (not associated to your user).

![screen shot 2016-02-03 at 10 33 27 am](https://cloud.githubusercontent.com/assets/796368/12789065/dddcf3ca-ca61-11e5-86bf-ffa076b8d791.png)
![screen shot 2016-02-03 at 10 31 50 am](https://cloud.githubusercontent.com/assets/796368/12789026/b694c7b6-ca61-11e5-823a-9a97e3969526.png)

Here is a help article with more context and information about this:
https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#you-havent-added-your-local-git-commit-email-to-your-profile

**Comment by druc** [comment]
Thanks for letting me know! :+1:
